name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-dotnet:
    name: Test .NET Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      - name: Restore Dependencies
        run: dotnet restore ./Api/ApiMicroservice.csproj

      - name: Run Tests
        run: |
          dotnet test --no-build --verbosity normal  || echo "Test failed" > test-error.log
        continue-on-error: true
        

  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test-dotnet
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/api:${{ github.sha }} ./Api/
      
      - name: Push Docker Image
        run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/api:${{ github.sha }}


  deploy-server:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Image SHA
      run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

    - name: Update Helm Chart
      run: |
        git config --global user.email "${{ secrets.EMAIL_RECEIVER }}"
        git config --global user.name "${{ secrets.SERVER_USER }}"
        git clone https://"${{ secrets.SERVER_USER }}":"${{ secrets.CI_TOKEN }}"@github.com/Armen8793/gitops-dotnet-helm-argocd.git
        echo -e "image:\n  repository: docker.io/${{ secrets.DOCKER_USERNAME }}/api\n  tag: ${IMAGE_TAG}\n  pullPolicy: IfNotPresent" > /home/runner/work/gitops-dotnet-helm-argocd/gitops-dotnet-helm-argocd/gitops-dotnet-helm-argocd/helmchart/apimicroservice/values-tag.yaml
        git add -A && git commit -m "Update image tag to ${IMAGE_TAG}"
        git push https://"${{ secrets.SERVER_USER }}":"${{ secrets.CI_TOKEN }}"@github.com/Armen8793/gitops-dotnet-helm-argocd.git HEAD:main        
        
  notify:
    name: Notify User
    runs-on: ubuntu-latest
    needs: [test-dotnet, build-docker, deploy-server]
    if: always()
    steps:
      - name: Send Success Email
        if: ${{ needs.test-dotnet.result == 'success' && needs.build-docker.result == 'success' && needs.deploy-server.result == 'success' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI/CD Pipeline Completed Successfully"
          body: |
            Pipeline completed successfully.
            All jobs succeeded:
            - Test .NET Code
            - Build and Push Docker Image
            - Deploy to Server
          to: ${{ secrets.EMAIL_RECEIVER }}
          from: GitHub <no-reply@github.com>
          
      - name: Send Failure Email
        if: ${{ needs.test-dotnet.result != 'success' || needs.build-docker.result != 'success' || needs.deploy-server.result != 'success' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI/CD Pipeline Failed"
          body: |
           Pipeline failed. Check the following jobs:
            - Test .NET Code: ${{ needs.test-dotnet.result }}
            - Build and Push Docker Image: ${{ needs.build-docker.result }}
            - Deploy to Server: ${{ needs.deploy-server.result }}
          to: ${{ secrets.EMAIL_RECEIVER }}
          from: ${{ secrets.EMAIL_SENDER }}
